# Copyright (C) 2023 Ibrahem Mouhamad
#
# SPDX-License-Identifier: MIT

FROM node:lts-slim AS booklist-ui

ARG http_proxy
ARG https_proxy
ARG no_proxy
ARG socks_proxy

ENV TERM=xterm \
    http_proxy=${http_proxy}   \
    https_proxy=${https_proxy} \
    no_proxy=${no_proxy} \
    socks_proxy=${socks_proxy} \
    LANG='C.UTF-8'  \
    LC_ALL='C.UTF-8'

# Install dependencies
COPY package.json /tmp/
COPY yarn.lock /tmp/
COPY booklist-ui/package.json /tmp/booklist-ui/

# Install common dependencies
WORKDIR /tmp/
RUN yarn install --ignore-scripts

# Build source code
COPY booklist-ui/ /tmp/booklist-ui/
RUN yarn run build:booklist-ui

FROM nginx:1.23.1-alpine
# Replace default.conf configuration to remove unnecessary rules
RUN sed -i "s/}/application\/wasm wasm;\n}/g" /etc/nginx/mime.types
COPY booklist-ui/react_nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=booklist-ui /tmp/booklist-ui/build /usr/share/nginx/html/