# Generated by Django 4.2 on 2023-04-30 05:23

import django.core.validators
from django.db import migrations, models

from booklist.apps.core.utils import get_book_column_names

def add_preset_data(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    for column_name in get_book_column_names():
        Profile.objects.create(column_name=column_name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('column_name', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(add_preset_data)
    ]
